### PR TITLE
Align EZID plugin as extension of Crossref plugin

### PR DESCRIPTION
**Pull request by ctgraham**
This PR is offered primarily for testing/review.  I think it is the direction we should go, but I don't think I've personally tested it sufficiently.

I _think_ this introduces no functional changes.

### CODE REVIEW

**Comment by logpanic** [comment]
I made a copy of this branch earlier and added a helper function and edited some others in EzidExportDom. I just did some very basic tests, and I was able to register multiple issues. I'll continue to test.

I also submitted my edited branch to yours as a PR, similarly for review.

**Comment by ctgraham** [comment]
After testing, this should probably be squashed before accepting the PR.

**Comment by ctgraham** [comment]
@chasehd, I've squashed the commits we've been working on, and I think we're closer, but something is still off about the Issue XML.  When I try to register a new Issue DOI, the Crossref XML contains no doi_data element.  Since we don't really generate Issue DOIs, my test data is a little scant.  Do you see what is missing?

**Comment by logpanic** [comment]
I cloned a copy of your remove-unneeded-code branch and this is what I get:
Article export:
https://gist.github.com/chasehd/8c404d8d114831105641
The collection node is inside the doi_data node; the collection node needs to be a sibling not a child of doi_data node.

Issue export:
https://gist.github.com/chasehd/aea02227030623119099

No article information or doi information is created in the xml export. Is this similar to your output?

**Comment by ctgraham** [comment]
When I try to [validate your Article export with Crossref](http://www.crossref.org/02publishers/parser.html), I get: `Invalid content was found starting with element 'journal_volume'. One of '{"http://www.crossref.org/schema/4.3.3":contributors, "http://www.crossref.org/schema/4.3.3":publication_date}' is expected.`.  That seems odd.  Do you get the same XML content if you use the Crossref plugin export directly?

My reading of the [4.3.3 schema](http://doi.crossref.org/schemas/crossref4.3.3.xsd) and [4.3.2 common](http://doi.crossref.org/schemas/common4.3.2.xsd) is that collection is a child of doi_data.  Where do you see it as a sibling?

I get a similar issue to your sample with the issue export.  I think it is a bug in DOIExportDom::retrieveArticlesByIssue() when 'articlesByIssue' is cached.  The code looks correct in [OJS master](https://github.com/pkp/ojs/blob/master/plugins/importexport/datacite/classes/DOIExportDom.inc.php#L320), but not [2.x dev](https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/importexport/datacite/classes/DOIExportDom.inc.php#L340)

**Comment by ctgraham** [comment]
I think the construction of the Issue XML will be corrected by https://github.com/pkp/pkp-lib/issues/798 and https://github.com/pkp/ojs/pull/630.

**Comment by logpanic** [comment]
When I try to register an article, I get this error: 

Registration was not successful! The DOI registration server returned an error: '400 - error: bad request - element 'crossref': <doi_data> element contains disallowed <collection> subelement'.

That's what made me think it needed to be a sibling. When I look back at older exports, the collection node isn't present.

**Comment by logpanic** [comment]
Also, in regards to the validation error you received, I tried adding a publication data to an issue. Once I did, I receive a 500 request error when I try to register or export any article from that issue.

**Comment by ctgraham** [comment]
Damn.  Yes, doi_data is a required element of journal_article and EZID wants the doi_data element to only contain doi and resource elements.  Getting rid of the collection element is [trivial](https://github.com/ulsdevteam/EzidDOI/commit/71f33762592cbc5672a1a93156b20cad99db26f7).  Regarding removing the articles from the issue XML, can you comment on [whether this is even desired functionality](https://github.com/VTUL/EzidDOI/issues/6#issuecomment-143742626)?  Does the Crossref plugin focus on articles (instead of issues) intentionally, or incidentally?

**Comment by ctgraham** [comment]
I validated this last change against Crossref's validation and a test registration with EZID.  After all that, I think we're back [pretty close to your initial code](https://github.com/chasehd/EzidDOI/commit/6088bd0fae8fd86fa9a82d01401c2df3fd320a9b).

**Comment by logpanic** [comment]
With regard to Crossref's focus, I only have assumptions. Ezid allows for the doi and resource nodes to be blank, which are subsequently filled via minting, if desired. Does the Crossref plugin does this? If not, it could explain why it requires articles to have DOIs and filters accordingly. Thoughts?

**Comment by ctgraham** [comment]
I'm not really sure myself.  I understand why it would require DOIs on the article level, as the presumption is that OJS will supply the DOI to Crossref (contra EZID's "minting" concept).  My uncertainty is the discrepancy between the Crossref plugin's idea that "you can't register an issue if it doesn't contain a published article" and my reading of EZID that an issue is registered independently of the articles.  I'll ask my publishing folks.

**Comment by ctgraham** [comment]
Please test to see if the PR maintains all of your expected functionality.  I believe these changes resolve our discussion within https://github.com/VTUL/EzidDOI/issues/3.

**Comment by logpanic** [comment]
Sorry. I'll try to review these PRs either today or tomorrow.

**Comment by logpanic** [comment]
Everything seems to work as intended; however, a doi_data node isn't added to the issue xml, so issue registration fails. And it still depends on https://github.com/pkp/pkp-lib/pull/769 being pushed to the stable branch.

**Pull request merged**
